spring:
  config:
    activate:
      on-profile: smtp-relay
  mail:
    host: ${SPRING_MAIL_HOST:smtp.example.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
          ssl:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE:false}
            trust: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST:}
          connectiontimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT:5000}
          timeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT:5000}
          writetimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT:5000}

app:
  notification:
    email:
      provider: ${APP_NOTIFICATION_EMAIL_PROVIDER:smtp}
      from-address: ${APP_NOTIFICATION_EMAIL_FROM_ADDRESS:${SPRING_MAIL_USERNAME:no-reply@weather-alert.local}}
    verification:
      send-email: ${APP_NOTIFICATION_VERIFICATION_SEND_EMAIL:true}
